name: Alpine
favicon: null
layout_spectrum: 0.0768
typography_spectrum: 0.38106
title: Alpine Adventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#8d8b99'
    - '#fec195'
    - '#2d2d2d'
    - '#a95c3a'
  brandStrength: 0.8386868999805301
  lightness: 0.4761570356786251
  saturation: 0.9321745398920029
  rhythmicContrast: 0.4819098892621696
purpose: []
