name: Alpine
favicon: null
layout_spectrum: 0.07954987790435553
typography_spectrum: 0.7242305802647024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8386868999805301
  lightness: 0.4761570356786251
  saturation: 0.9321745398920029
  rhythmicContrast: 0.4819098892621696
purpose: []
